static void scroller(Monitor *m);
static void normalizecols(Monitor *m);
static Client *nextcol(Client *c);
static int colcount(Monitor *m);
static int colwidthof(Monitor *m, int col);
static int colx(Monitor *m, int col);
static void setcolfact(const Arg *arg);
static void setcolwidth(const Arg *arg);
static void maximizecol(const Arg *arg);
static void scrolltogglefullscr(const Arg *arg);
static void syncfullscreen(Monitor *m, Client *sel);
static void gathercolumns(const Arg *arg);
static void scrolltogglefloating(const Arg *arg);
static void dropfullscreen(Monitor *m, Client *keep);
static void scrolltocol(Monitor *m, int col);
static Client *colclient(Monitor *m, int col);
static void insertcolumn(Client *c);
static void setclientscroller(Client *c);
static int getclientscroller(Client *c);
static void focuscol(const Arg *arg);
static void focusincol(const Arg *arg);
static void movecol(const Arg *arg);
static void listswap(Monitor *m, Client *a, Client *b);
static void consumeexpel(const Arg *arg);
static void moveincol(const Arg *arg);
static void scrollfocus(const Arg *arg);
static void scrollfocusstack(const Arg *arg);
static void scrollmove(const Arg *arg);
